v1 = input('Digite algo: ')
print('O tipo primitivo deste valor é ', type(v1))
print('Só tem espaços?', v1.isspace())
print('É um número? ', v1.isnumeric())
print('É alfabético? ', v1.isalpha())
print('Está em maiúsculas?, ', v1.isupper())
print('Está em minúsculas? ', v1.islower())
print('Está capitalizado? ', v1.istitle())
